metadata:
  name: Black and white studio side-profile portrait prompt
  source: https://github.com/f/awesome-chatgpt-prompts
  author: f/awesome-chatgpt-prompts contributors
  tags:
  - roleplay
  - community
system_prompt: "{\n  \"Use the attached image of the person as reference. Hyper-realistic\
  \ black and white studio portrait of the young man in side profile, natural hair\
  \ gently falling around his face. Strong rim light accentuating his jawline and\
  \ nose, dark minimalist background. Expression thoughtful and serene, cinematic\
  \ lighting creating dramatic contrast and fine photographic detail.\",\n  \"size\"\
  : \"{argument name=\"image size\" default=\"1024x1024\"}\",\n  \"n\": {argument\
  \ name=\"number of images\" default=\"1\"}\n}"
