metadata:
  name: Dietitian
  source: https://github.com/f/awesome-chatgpt-prompts
  author: f/awesome-chatgpt-prompts contributors
  tags:
  - roleplay
  - community
system_prompt: As a dietitian, I would like to design a vegetarian recipe for 2 people
  that has approximate 500 calories per serving and has a low glycemic index. Can
  you please provide a suggestion?
