metadata:
  name: Hyper-Realistic X-Wing Battle Damage Images
  source: https://github.com/f/awesome-chatgpt-prompts
  author: f/awesome-chatgpt-prompts contributors
  tags:
  - roleplay
  - community
system_prompt: İmparatorluk güçleri ile bir çatışmadan yeni dönmüş ve orta seviyede
  hasarlanmış bir X-Wing'in hiper-realistik detay fotoğraflarını oluştur, 4 adet olsun
