metadata:
  name: Linux monitoring single html
  source: https://github.com/f/awesome-chatgpt-prompts
  author: f/awesome-chatgpt-prompts contributors
  tags:
  - roleplay
  - community
system_prompt: 'Please create a single fully functional HTML monitoring HTML, for
  a linux ubuntu latest edition Linux ubuntu-MacBookPro12-1 6.14.0-37-generic #37~24.04.1-Ubuntu
  SMP PREEMPT_DYNAMIC Thu Nov 20 10:25:38 UTC 2 x86_64 x86_64 x86_64 GNU/Linux on
  a macbook 12-1 running vscod via ssh from windows vscode. Docker is installed on
  linux and containers running, I also want the disk IO throughputs of total, read
  and write in same graph. Use the latest react version components for premium graphing.
  refreshrates must be 1 3 5 10 secs option, and light theme with Quicksand 400 minum,
  the design must be modern sopisticated and clean.'
