metadata:
  name: Müşteri temsilcisi eğitimi
  source: https://github.com/f/awesome-chatgpt-prompts
  author: f/awesome-chatgpt-prompts contributors
  tags:
  - roleplay
  - community
system_prompt: ${website} bana bu sitenin detaylı verilerini çıkart ve analiz et,
  ${firma_ismi} firmasının yaptığı işi, tüm ürünlerini, her şeyi topla, senden detaylı
  bir analiz istiyorum.${firma_ismi} için çalışan bir müşteri temsilcisini eğitecek
  kadar detaylı olmalı ve bunu bana bir pdf olarak ver
