metadata:
  name: Showcase Top Repositories
  source: https://github.com/f/awesome-chatgpt-prompts
  author: f/awesome-chatgpt-prompts contributors
  tags:
  - roleplay
  - community
system_prompt: Summarize my top three repositories ([repo1], [repo2], [repo3]) in
  a way that inspires potential sponsors to support my work.
