metadata:
  name: Subject meditating in a crystal sphere
  source: https://github.com/f/awesome-chatgpt-prompts
  author: f/awesome-chatgpt-prompts contributors
  tags:
  - roleplay
  - community
system_prompt: a transparent crystal portal floating in the middle of clouds in the
  sky, with a ${subject}, sitting inside meditating with golden lights coming up from
  all their chakras, 2 other light beams are traversing their body one from top to
  bottom and 2 diagonally
